# Some settings are automatically inherited from .editorconfig
semi: false
trailingComma: all
singleQuote: true
overrides:
  - files: ".editorconfig"
    options:
      parser: yaml
  - files: "LICENSE"
    options:
      parser: markdown
